### ISSUE TITLE
'TSDF' object has no attribute 'Interpolation' 

### ISSUE THREAD

**Issue by BenLBurke** [databrickslabs/tempo#188]
I'm running TSDF on my DBR 10.3 ML spark cluster within Databricks. 

After converting my df to a TSDF I try to apply the 'linear' interpolation to it: 

`longTSDF = TSDF(longDF, ts_col="values", partition_cols="filename")`

`interLongTSDF = longTSDF.interpolate(method="linear")`

But get the error no method exists:

`'TSDF' object has no attribute 'interpolation' `

Any help? I tried installing tempo to both to my cluster and via a pip install within the notebook, both to no avail.

**Comment by guanjieshen** [comment]
Hi @BenLBurke if you are not resampling using the `resample` first, you will need to specify a few additional parameters in addition to `method`:

```python
interpolated_tsdf = input_tsdf.interpolate(
    freq="30 seconds",
    func="mean",
    method="linear"
)
```

Alternatively can do something like this:

```python
interpolated_tsdf = input_tsdf.resample(freq="30 seconds", func="mean").interpolate(
    method="linear"
)
```

**Comment by guanjieshen** [comment]
@BenLBurke Which version of tempo do you have installed? We recommend version using `1.12` or higher.

**Comment by BenLBurke** [comment]
Thanks @rportilla-databricks I did verify I am running version `0.1.2`. 

I'm running on a 10.3 ML runtime (Spark 3.2.1, Scala 2.12)

Am I install the right package: `pip install dbl-tempo`?

Here is my full code:

`import tempo`

`tsDF = tempo.TSDF(DF, ts_col="Timestamp", partition_cols='FileName')`

`tsDF = tsDF.resample(freq='30 sec', func='mean', metricCols=['values']).interpolate(method = 'linear)`

Return:
**Attribution Error**: 'TSDF' object has no attribute 'interpolate'

**Comment by rportilla-databricks** [comment]
@BenLBurke, I see the issue. Your version (0.1.2) does not have the interpolation feature. We released this functionality in 0.1.3 and have since made enhancements which allow for the simpler arguments you are using above. We recommend starting with 0.1.12 and ideally use the latest version of tempo.

**Comment by BenLBurke** [comment]
Got it to work on 0.1.12.

Thank you for your help @rportilla-databricks & @guanjieshen .
